name: chatapp_firebase
description: A new Flutter project.

# Prevent accidental publishing
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0" # Updated to support newer Dart versions

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0 # Updated for compatibility with latest Flutter and Firebase
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  shared_preferences: ^2.1.0 # Updated to the latest version
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  google_fonts: ^4.0.4 # Use the latest version

dev_dependencies:
  flutter_lints: ^5.0.0 # Slightly updated version
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
